version: '3.9'

services:
  dev:
    container_name: dev
    build: ./
    network_mode: host

  prod:
    container_name: dev
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json
